### ISSUE TITLE
Youtube channel activismeBE

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Internals#14]

**Comment by ghost** [comment]
YouTube Channel created and tested. WORKS flawless!

**Comment by ghost** [comment]
Only 1 thing.. Have to make YouTube cover art for YouTube. So this ticket will remain open when it's all set and done.

**Comment by Tjoosten** [comment]
@ubextreme Status update

**Comment by Tjoosten** [comment]
@ubextreme @alfamongrel  Status update about the ticket?

**Comment by Tjoosten** [comment]
Closed due activity.
