### ISSUE TITLE
duidelijk overzicht in GIT

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/Internals#29]
eens duidelijk de titels in GIT die niet meer gebruikt worden aangeven !

**Comment by Tjoosten** [comment]
`DEPRACTED-` prefix is toegevoegd aan de namen 

**EDIT:** Niet ondersteunde repositories zijn verhuisd naar onze archive organisatie

**Comment by Tjoosten** [comment]
Heropend wegens: herstructureringen in de organisatie labels, issues

**Comment by Tjoosten** [comment]
Tot nader overzicht hoort de deployment documentatie niet bij het git overzicht
