### ISSUE TITLE
Opname van Ben in de organisatie.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Internals#30]
Nu dat @TeppersBen al een tijdje meedraait met ons. (klein subtiel vreugde dansje). 

Zou ik graag Ben graag opnemen als vaste bijdrager aan onze platformen. 

Als het goed is voor @alfamongrel zou ik hem een developer role op de ACL in onze server geven. Met een email adres op onze domein naam. Plus verder zou ik hem ook als hij het ziet zitten meer verantwoordelijkheid willen geven in Front-end development. 

En verplaatsen van team (Developers naar Administrators). 

@TeppersBen zie jij dat zitten. Indien ja moet er is met @alfamongrel vergaderd worden omtrent opsplitsing van de de taken. 

@alfamongrel Ook jij hebt inspraak. Indien vragen hoor ik deze graag.

**Comment by TeppersBen** [comment]
Dit zie ik helemaal zitten 👍

**Comment by Tjoosten** [comment]
@alfamongrel CC: @TeppersBen Ook zouden aan Ben eventueel SMTP testing gegevens moeten gegeven worden. Voor tijdens de ontwikkeling van applicaties en back-end

**Comment by alfamongrel** [comment]
ok dus maken we mail adres aan en een gebruiker voor de server ?

**Comment by Tjoosten** [comment]
Email en login op de platformen.
