### ISSUE TITLE
Open-source van onze GEO dataset.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Internals#31]
Aangezien we voor activisme_BE een dataset gebruiken voor geo data. En op latere basis GEO allocatie. Zouden we dit deel van de database moeten open-sourcen. Zodat het beheer van deze gegevens optimaler verloopt. 

Het zou gaan om currencies, countries, continents, belgian_cities, provinces.

**Comment by Tjoosten** [comment]
@alfamongrel CC: @TeppersBen Ook zouden aan Ben eventueel SMTP testing gegevens moeten gegeven worden. Voor tijdens de ontwikkeling van applicaties en back-end

**Comment by alfamongrel** [comment]
ok

**Comment by Tjoosten** [comment]
Sorteer algoritme voor de stads sortering en selectering: 

```sql
SELECT t1.postal_code, t1.city_name, t1.lat_num, t1.lng_num, t2.province_name_nl, t2.province_name_fr, t2.province_name_de
     FROM activisme_dev.cities AS t1
          JOIN activisme_dev.provinces as t2
             ON t1.province_id = t2.id
    ORDER BY t1.city_name ASC;
```

**Comment by Tjoosten** [comment]
**UPDATE:** De repository hiervoor is aangemaakt

**Comment by Tjoosten** [comment]
Dit ticket word gesloten. ALLE ticketten omtrent dit onderwerp moeten geplaatst worden onder de bijhorende repository.
