### ISSUE TITLE
Implementatie documentatie labels

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Internals#33]
REF #29 | Duidelijk overzicht in GIT. 

Voor nu hebben labels die we standaard gebruiken doorheen onze repositories. 
Deze zouden gedocumenteerd moeten staan in onze internals. 

Ik denk dat we dit het beste kunnen doen in onze Tagging-styleguide. Maar ben niet zeker. Suggesties? @alfamongrel @TeppersBen 

### Overzicht labels:

| Naam | Kleur code: |
| :------ | :-----------  |
| Bug	|		`#d93f0b` |
| Chore		|	`#0e8a16` |
| Confirmed |		`#d93f0b` |
| Cricitcal priority | 	`#b60205` |
| Discussion	|	`#1d76db` |
| Duplicate	|	`#d4c5f9` |
| Enhancement |		`#fef2c0` |
| Feature	|		`#fef2c0` |
| High Priority |		`#e99695` |
| In Progress |		`#fbca04` |
| Invalid	|		`#d4c5f9` |
| Legal	|		`#5319e7` |
| Low Priority	|	`#e99695` |
| Medium Priority |		`#e99695` |
| On Hold		|	`#d4c5f9` |
| Optimalization	|	`#0e8a16` |
| Question	| 	`#1d76db` |
| Security	 |	`#d93f0b` |
| Wontfix		|	`#d4c5f9` |

**Comment by alfamongrel** [comment]
deftig gedacht
