### ISSUE TITLE
voledig CSS systeem voor elke Crowdfund

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/Internals#48]
er moet een volledig onafhankelijk 3 talig systeem opgemaakt worden voor elke Crowdfund die we doen !
waar we makkelijk Crowdfunds kunnen aanmaken en verwijderen !
ref #47

**Comment by Tjoosten** [comment]
Aanmaken en verwijderen is back-end


2017-06-19 22:17 GMT+02:00 Tom Manhaeghe <notifications@github.com>:
